"""removed the description column from moods table

Revision ID: 4d1570cad9b3
Revises: eeeaedf05966
Create Date: 2025-12-03 08:53:52.812727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1570cad9b3'
down_revision: Union[str, None] = 'eeeaedf05966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moods', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moods', sa.Column('description', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
